@startuml
object "titanic : Ship" as titanic {
    shipName = "Titanic"
    yearBuilt = "March31st,1909"
}
object "mvGemini : CruiseShip" as mvGemini {
    maxNumberPassengers = 100
}
object "mvGemini : Ship" as mvGeminiParent {
    shipName = "MVGemini"
    yearBuilt = "May30th,1991"
}
object "everGiven : CargoShip" as everGiven {
    cargoCapacityInTonnage = 220940
}
object "everGiven : Ship" as everGivenParent {
    shipName = "EverGiven"
    yearBuilt = "September25th,2018"
}

mvGeminiParent <|-- mvGemini
everGivenParent <|-- everGiven
@enduml
